version: '2'
services:
  talk:
    image: coralproject/talk:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.2
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:3.2
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
